
--==========================  SEQUENCES  =====================--

CREATE SEQUENCE PERMISSION_ID_SEQ START WITH 50;
CREATE SEQUENCE COORDINATE_ID_SEQ START WITH 110;
CREATE SEQUENCE LOCATION_ID_SEQ START WITH 2005;
CREATE SEQUENCE USER_ID_SEQ START WITH 1050;
CREATE SEQUENCE EVENT_ID_SEQ START WITH 50;
CREATE SEQUENCE EVENT_IMAGE_ID_SEQ START WITH 50;
CREATE SEQUENCE SKILL_MAP_ID_SEQ START WITH 5000;
CREATE SEQUENCE SKILL_DESCRIPTION_ID_SEQ START WITH 5000;
CREATE SEQUENCE EVENT_DESCRIPTION_ID_SEQ START WITH 5000;
CREATE SEQUENCE EVENT_TIME_ID_SEQ START WITH 5000;
CREATE SEQUENCE PARTICIPANT_ID_SEQ START WITH 5000;
CREATE SEQUENCE CONSTANT_ID_SEQ START WITH 1000;
CREATE SEQUENCE PROFILE_LINK_SEQ START WITH 1000;
CREATE SEQUENCE RATING_SEQ START WITH 5000;
CREATE SEQUENCE CATEGORY_SEQ START WITH 20;
CREATE SEQUENCE MESSAGE_ID_SEQ START WITH 20;
