
--==========================  SEQUENCES  =====================--

CREATE SEQUENCE PERMISSION_ID_SEQ;
CREATE SEQUENCE COORDINATE_ID_SEQ;
CREATE SEQUENCE LOCATION_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ START WITH 1050;
CREATE SEQUENCE EVENT_ID_SEQ;
CREATE SEQUENCE EVENT_IMAGE_ID_SEQ;
CREATE SEQUENCE SKILL_MAP_ID_SEQ;
CREATE SEQUENCE SKILL_DESCRIPTION_ID_SEQ;
CREATE SEQUENCE EVENT_DESCRIPTION_ID_SEQ;
CREATE SEQUENCE EVENT_TIME_ID_SEQ;
CREATE SEQUENCE PARTICIPANT_ID_SEQ;
CREATE SEQUENCE SKILL_ID_SEQ;
