
--==========================  TYPES  =====================--


--------- FORCE DROP DEPENDANT TYPES ----------
-- DROP TYPE DESCRIPTION_TABLE FORCE;
-- DROP TYPE DESCRIPTION_LIST_TABLE FORCE;


--------------- OBJECT TYPES ------------------
CREATE OR REPLACE TYPE DESCRIPTION_LIST AS OBJECT(
    ID NUMBER,
    POSITION NUMBER(3),
    TEXT VARCHAR(256)
);
/

CREATE OR REPLACE TYPE DESCRIPTION_TYPE AS OBJECT(
    ID NUMBER,
    TEXT CLOB
);
/


--------------- TABLE TYPES -----------------
CREATE OR REPLACE TYPE DESCRIPTION_TABLE IS TABLE OF DESCRIPTION_TYPE;
/

CREATE OR REPLACE TYPE DESCRIPTION_LIST_TABLE IS TABLE OF DESCRIPTION_LIST;
/
