
--==========================  TYPES  =====================--


--------- FORCE DROP DEPENDANT TYPES ----------
-- DROP TYPE DESCRIPTION_TABLE FORCE;
-- DROP TYPE DESCRIPTION_LIST_TABLE FORCE;


--------------- OBJECT TYPES ------------------
CREATE OR REPLACE TYPE DESCRIPTION_LIST AS OBJECT(
    ID NUMBER,
    POSITION NUMBER(3),
    TEXT VARCHAR(256)
);
/

CREATE OR REPLACE TYPE DESCRIPTION_TYPE AS OBJECT(
    ID NUMBER,
    TEXT CLOB
);
/

create or replace TYPE LINK_TYPE AS OBJECT (
    ID NUMBER,
    USER_ID NUMBER,
    CREATOR_ID NUMBER,
    IS_GOOD NUMBER(1),
    REASON VARCHAR2(256)
);
/

CREATE OR REPLACE TYPE PROFILE_LINK_TYPE AS OBJECT (
    ID NUMBER,
    USER_ID_1 NUMBER,
    USER_ID_2 NUMBER,
    CREATOR_ID NUMBER,
    IS_GOOD NUMBER(1),
    REASON VARCHAR(256)
);
/
--------------- TABLE TYPES -----------------
CREATE OR REPLACE TYPE DESCRIPTION_TABLE IS TABLE OF DESCRIPTION_TYPE;
/

CREATE OR REPLACE TYPE DESCRIPTION_LIST_TABLE IS TABLE OF DESCRIPTION_LIST;
/

CREATE OR REPLACE TYPE LINK_TABLE IS TABLE OF LINK_TYPE;
/

CREATE OR REPLACE TYPE NUMBER_ARRAY IS TABLE OF NUMBER;
/

CREATE OR REPLACE TYPE PROFILE_LINK_TABLE IS TABLE OF PROFILE_LINK_TYPE;
/
