
--==========================  FUNCTIONS  =====================--

-- THIS FUNCTION IS TO BE USED TO CONCATINATE
-- ALL TEXTS WITH THE TEXTS SHARING THE SAME ID
create or replace FUNCTION CONCATINATE_DESCRIPTIONS(DESC_LIST DESCRIPTION_LIST_TABLE)
    RETURN DESCRIPTION_TABLE
    IS
    TEXT CLOB;
    DESC_ID NUMBER;
    CURR_DESC_ID NUMBER;
    TBL_COUNT NUMBER;
    RET_VAL DESCRIPTION_TABLE := DESCRIPTION_TABLE();
    BEGIN

        DESC_ID := 0;
        FOR O IN (SELECT * FROM TABLE(DESC_LIST))
        LOOP
            CURR_DESC_ID := O.ID;

         IF CURR_DESC_ID != DESC_ID THEN
            RET_VAL.EXTEND;
            RET_VAL(RET_VAL.COUNT) := DESCRIPTION_TYPE(DESC_ID, TEXT);
            DESC_ID := CURR_DESC_ID;
            TEXT := '';
        END IF;

            TEXT := TEXT || O.TEXT;
        END LOOP;
        RET_VAL.EXTEND;
        RET_VAL(RET_VAL.COUNT) := DESCRIPTION_TYPE(CURR_DESC_ID, TEXT);
        RETURN RET_VAL;
    END;
/

-- THIS FUNCTION SIMPLY ORDERS THE EVENT_DESCRIPTION TABLE
-- ALLOWING CONCATINATE_DESCRIPTIONS TO CONCATINATE ALL WITH
-- THE SAME IDS IN THE ORDER DICTATED BY POSITION.
create or replace FUNCTION CONCAT_EVENT_DESC
    RETURN DESCRIPTION_TABLE
    IS
    DESC_LIST DESCRIPTION_LIST_TABLE;
    RET_VAL DESCRIPTION_TABLE := DESCRIPTION_TABLE();
    BEGIN
        SELECT * BULK COLLECT INTO DESC_LIST FROM
            (select DESCRIPTION_LIST(EVENT_ID, POSITION, DESCRIPTION)
            from EVENT_DESCRIPTION
            ORDER BY ID, POSITION);
        RETURN CONCATINATE_DESCRIPTIONS(DESC_LIST);
    END;
/

-- THIS FUNCTION SIMPLY ORDERS THE EVENT_DESCRIPTION TABLE
-- ALLOWING CONCATINATE_DESCRIPTIONS TO CONCATINATE ALL WITH
-- THE SAME IDS IN THE ORDER DICTATED BY POSITION.
create or replace FUNCTION CONCAT_SKILL_DESC
    RETURN DESCRIPTION_TABLE
    IS
    DESC_LIST DESCRIPTION_LIST_TABLE;
    RET_VAL DESCRIPTION_TABLE := DESCRIPTION_TABLE();
    BEGIN
        SELECT * BULK COLLECT INTO DESC_LIST FROM
            (select DESCRIPTION_LIST(SKILL_MAP_ID, POSITION, DESCRIPTION)
            from SKILL_DESCRIPTION
            ORDER BY ID, POSITION);
        RETURN CONCATINATE_DESCRIPTIONS(DESC_LIST);
    END;
/
