
--==========================  VIEWS  =====================--

CREATE VIEW EVENT_DESCRIPTION_TBL AS
    SELECT * FROM TABLE(CONCAT_EVENT_DESC) WHERE TEXT IS NOT NULL;

CREATE VIEW SKILL_DESCRIPTION_TBL AS
    SELECT * FROM TABLE(CONCAT_SKILL_DESC) WHERE TEXT IS NOT NULL;
