
--==========================  SkillMap Data  =====================--

INSERT INTO SKILL_MAP (ID, SKILL_ID, ATTRIBUTER_ID, RECIEVER_ID, VALUE) VALUES (1, 1, 2, 1, 9);
INSERT INTO SKILL_MAP (ID, SKILL_ID, ATTRIBUTER_ID, RECIEVER_ID, VALUE) VALUES (2, 2, 2, 1, 9);
INSERT INTO SKILL_MAP (ID, SKILL_ID, EVENT_ID, ATTRIBUTER_ID, RECIEVER_ID, VALUE) VALUES (3, 1, 1, 1, 2, 9);
