
--==========================  Coordinate Data  =====================--

INSERT INTO LOCATION (ID, USER_ID, COORDINATE_ID, NAME, RADIUS_METERS)
  VALUES (1, 1, 1, 'HOME', 25);
INSERT INTO LOCATION (ID, USER_ID, COORDINATE_ID, NAME, RADIUS_METERS)
  VALUES (2, 1, 2, 'WORK', 512);
