
--==========================  Participant Data  =====================--

INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (1, 1, 1);
INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (2, 1, 2);
INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (3, 1, 3);
INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (4, 1, 4);
INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (5, 1, 5);
INSERT INTO PARTICIPANT (ID, EVENT_TIME_ID, USER_ID) VALUES (6, 1, 6);
