
--==========================  Rating Data  =====================--

INSERT INTO RATING
    (ID, ATTRIBUTER_ID, RECIEVER_ID, DESCRIPTION, TIME_STAMP, VALUE, ATTRIBUTER_SNAPSHOT_RATING)
    VALUES (1, 2, 1, 'Joy to work with!', TO_TIMESTAMP('10-SEP-0214:10:10.123000','DD-MON-RRHH24:MI:SS.FF')
    , 9, 7);

INSERT INTO RATING
    (ID, ATTRIBUTER_ID, RECIEVER_ID, DESCRIPTION, TIME_STAMP, VALUE, ATTRIBUTER_SNAPSHOT_RATING)
    VALUES (2, 5, 1, 'He is a vicious beast!', TO_TIMESTAMP('10-OCT-0214:10:10.123000','DD-MON-RRHH24:MI:SS.FF')
    , 0, 9);

INSERT INTO RATING
    (ID, ATTRIBUTER_ID, RECIEVER_ID, DESCRIPTION, TIME_STAMP, VALUE, ATTRIBUTER_SNAPSHOT_RATING)
    VALUES (3, 4, 1, 'I like chicken I like liver...', TO_TIMESTAMP('10-NOV-0214:10:10.123000','DD-MON-RRHH24:MI:SS.FF')
    , 9, 1);
